### ISSUE TITLE
Author 008-a: Create Basic Stream Post

### ISSUE THREAD

**Issue by forgeno** [forgeno/CMPUT404-group-project#27]
User should be able to create a basic post
title
description
content
author
categories
published date/time
content type: text/plain, markdown, image/png;base64, image/jpg;base64, image/png;base64 w/ text
privacy buttons

**Comment by hiufungk** [comment]
support attributes in #21

**Comment by shchau** [comment]
Poopy-di scoop
Scoop-diddy-whoop
Whoop-di-scoop-di-poop
Poop-di-scoopty
Scoopty-whoop
Whoopity-scoop, whoop-poop
Poop-diddy, whoop-scoop
Poop, poop
Scoop-diddy-whoop
Whoop-diddy-scoop
Whoop-diddy-scoop, poop
